SELECT VERSION();


CREATE TABLE hmsapi.API_LOG(
	MBRSH_PGM_ID VARCHAR(1) NOT NULL,
	API_ID VARCHAR(50) NOT NULL,
	REQ_SEQ INT auto increment NOT NULL,
	REQ_DTM VARCHAR(14) NOT NULL,
	TRAC_NO VARCHAR(20) NOT NULL,
	ANS_CD VARCHAR(6) NOT NULL,
	ANS_MSG VARCHAR(100) NOT NULL,
	REQ_KEY VARCHAR(100) NOT NULL,
	REQ_DATA VARCHAR(4000),
	RES_DATA VARCHAR(4000),
	PRIMARY KEY(MBRSH_PGM_ID, API_ID, REQ_SEQ, REQ_DTM)
);


SELECT * FROM API_LOG;


--oracle

CREATE TABLE API_LOG 
( 
	MBRSH_PGM_ID VARCHAR2(1) NOT NULL,
	API_ID VARCHAR2(50) NOT NULL,
	REQ_SEQ NUMBER GENERATED AS IDENTITY NOT NULL,
	REQ_DTM VARCHAR2(14) NOT NULL,
	TRAC_NO VARCHAR2(20) NOT NULL,
	ANS_CD VARCHAR2(6) NOT NULL,
	ANS_MSG VARCHAR2(100) NOT NULL,
	REQ_KEY VARCHAR2(100) NOT NULL,
	REQ_DATA VARCHAR2(4000),
	RES_DATA VARCHAR2(4000),
    CONSTRAINT API_LOG_PK PRIMARY KEY (MBRSH_PGM_ID, API_ID, REQ_SEQ, REQ_DTM)
);