spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:mysql://146.56.131.188:35306/hmsapi?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul"
      #url: jdbc:log4jdbc:mariadb://146.56.131.188:35306/hmsapi?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
      username: hmsadm
      password: "!@Admin1234"
      driver-class-name: com.mysql.cj.jdbc.Driver
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-jiniworld
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 240000
      
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    rolling-file-name: "C:/dev/logs/abc.%d{yyyy-MM-dd}.%i"
  file:
    name: "C:/dev/logs/abc.log"
    max-history: 30
  level:
    org:
      springframework: INFO
      
jwt:
  key: HMS_TOKEN_SECRET_KEY
  expiredTime: 120